### ISSUE TITLE
NoSuchMethodError: io.realm.RealmResults.sort

### ISSUE THREAD

**Issue by MohMah** [PhilJay/MPAndroidChart#1823]
Hi,
I setup the line chart example with realm and when I run it it gives me this error:
```
java.lang.NoSuchMethodError: io.realm.RealmResults.sort
       at com.github.mikephil.charting.data.realm.base.RealmBaseDataSet.<init>(RealmBaseDataSet.java:72)
```
I'm using the classpath realm plugin `classpath "io.realm:realm-gradle-plugin:0.90.1"` and MPAndroid uses `provided 'io.realm:realm-android:0.87.5' `, could this be the reason??

**Comment by MohMah** [comment]
I copied library code into my project and removed MPAndroid dependency from `build.gradle` and it worked. I think you should update realm version of the library to the latest version

**Comment by fettlaus** [comment]
Same problem here. I can't seem to get it to work with Realm 1.0.0.
I'd really like to use this feature.

**Comment by Rohitp** [comment]
Same error. I'm just manually cycling through the Realm result set for now

**Comment by PhilJay** [comment]
I am aware of the issue, the new release v3.0.0 will contain a fix and allow to use the latest realm version.

**Comment by pazaan** [comment]
Is there a workaround for this until v3.0.0 is released?

**Comment by fettlaus** [comment]
Just cycle through your ResultSet manually. It's the simplest way for now.
Am 20.06.2016 11:44 schrieb "Lennart Goedhart" <notifications@github.com>:

**Comment by PhilJay** [comment]
All realm related features have now been moved to a separate repository: [MPAndroidChart-Realm](https://github.com/PhilJay/MPAndroidChart-Realm).

This library is based on the latest version of realm.
