### ISSUE TITLE
Cannot compile after update to 2.2.0

### ISSUE THREAD

**Issue by Pitel** [PhilJay/MPAndroidChart#1381]
```java
final BarDataSet dataSet = barChartView.getData().getDataSetByIndex(0);
```

```
error: incompatible types: IBarDataSet cannot be converted to BarDataSet
```

**Comment by Pitel** [comment]
Ok, I probably fixed it by simply using `IBarDataSet` instead of `BarDataSet`.

But now I noticed there is no `removeEntry(int)` method for remove entry on given index. And it was there!

**Comment by PhilJay** [comment]
You are right, I forgot to include those in the new interfaces.

I will correct that soon. In the meantime a workaround could be casting `IBarDataSet` to `BarDataSet`, that should work.
